CREATE PROCEDURE SP_SupprimerSousFamille

( @SF_ID INT )

AS 

 BEGIN TRAN

 ALTER TABLE MARQUE
 NOCHECK CONSTRAINT FK_MARQUE_ASSOCIATI_SOUS_FAM

 DELETE FROM MARQUE  WHERE MARQUE.SF_ID=@SF_ID
 
 DELETE FROM SOUS_FAMILLE WHERE SOUS_FAMILLE.SF_ID=@SF_ID

 
 ALTER TABLE MARQUE
 CHECK CONSTRAINT FK_MARQUE_ASSOCIATI_SOUS_FAM

 COMMIT TRAN