USE [IN5_CAISSE]
GO

/****** Object:  StoredProcedure [dbo].[SP_SupprimerCaisse]    Script Date: 04/25/2012 11:56:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[SP_SupprimerCaisse]
( @CAISSE_ID int )

AS 

BEGIN TRANSACTION

ALTER TABLE OCCUPATION 
NOCHECK CONSTRAINT FK_OCCUPATI_ASSOCIATI_CAISSIER

ALTER TABLE CLOTURE 
NOCHECK CONSTRAINT FK_CLOTURE_ASSOCIATI_CAISSE

delete from CAISSE where CAISSE.CAISSE_ID=@CAISSE_ID

delete from OCCUPATION WHERE OCCUPATION.CAISSE_ID=@CAISSE_ID

DELETE FROM CLOTURE WHERE CLOTURE.CAISSE_ID=@CAISSE_ID

ALTER TABLE OCCUPATION 
CHECK CONSTRAINT FK_OCCUPATI_ASSOCIATI_CAISSIER

ALTER TABLE CLOTURE 
CHECK CONSTRAINT FK_CLOTURE_ASSOCIATI_CAISSE

COMMIT TRANSACTION
GO


