CREATE PROCEDURE SP_SupprimerTicket

(@TIK_ID INT )

 AS
 
BEGIN TRAN

 ALTER TABLE PAYEMENT_OF_TICKET
 NOCHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__TICKET

 DELETE FROM PAYEMENT_OF_TICKET WHERE PAYEMENT_OF_TICKET.TIK_ID=@TIK_ID
 
 DELETE FROM TICKET WHERE TICKET.TIK_ID=@TIK_ID

 ALTER TABLE PAYEMENT_OF_TICKET
 CHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__TICKET

COMMIT TRAN