CREATE PROCEDURE SP_SupprimerCodeBarre
( @CB_ID int )
 
AS 

BEGIN TRANSACTION

 ALTER TABLE ARTICLE
 NOCHECK CONSTRAINT FK_ARTICLE_ASSOCIATI_CODE_BAR

 DELETE FROM CODE_BARE WHERE CODE_BARE.CB_ID=@CB_ID

 DELETE FROM ARTICLE WHERE ARTICLE.CB_ID=@CB_ID

 ALTER TABLE ARTICLE
 CHECK CONSTRAINT FK_ARTICLE_ASSOCIATI_CODE_BAR

 COMMIT TRANSACTION