CREATE PROCEDURE SP_SupprimerTarif

( @TRF_ID INT )

AS 

BEGIN TRANSACTION 

 ALTER TABLE TARIF_OF_ARTICLE
 NOCHECK CONSTRAINT FK_TARIF_OF_TARIF_OF__TARIF

 DELETE FROM TARIF_OF_ARTICLE WHERE TARIF_OF_ARTICLE.TRF_ID=@TRF_ID
 
 DELETE FROM TARIF WHERE TARIF.TRF_ID=@TRF_ID

 ALTER TABLE TARIF_OF_ARTICLE
 CHECK CONSTRAINT FK_TARIF_OF_TARIF_OF__TARIF
 
COMMIT TRANSACTION