CREATE PROCEDURE SP_SupprimerFacture

( @FACT_ID INT )

AS 

BEGIN TRANSACTION 

 ALTER TABLE PAYEMENT_OF_FACTURE
 NOCHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__FACTURE

 DELETE FROM PAYEMENT_OF_FACTURE WHERE PAYEMENT_OF_FACTURE.FACT_ID=@FACT_ID
 
 DELETE FROM FACTURE WHERE FACTURE.FACT_ID=@FACT_ID

 ALTER TABLE PAYEMENT_OF_FACTURE
 CHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__FACTURE
 
COMMIT TRANSACTION