USE [IN5_CAISSE]
GO

/****** Object:  StoredProcedure [dbo].[SP_SupprimerFamille]    Script Date: 04/25/2012 12:06:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_SupprimerFamille]
( @FML_ID INT )

AS 

BEGIN TRAN

 ALTER TABLE SOUS_FAMILLE
 NOCHECK CONSTRAINT FK_SOUS_FAM_CONTIENT_FAMILLE

 DELETE FROM FAMILLE WHERE FAMILLE.FML_ID=@FML_ID

 DELETE FROM SOUS_FAMILLE WHERE SOUS_FAMILLE.FML_ID=@FML_ID

 ALTER TABLE SOUS_FAMILLE
 CHECK CONSTRAINT FK_SOUS_FAM_CONTIENT_FAMILLE

COMMIT TRAN

GO


