CREATE PROCEDURE SP_SupprimerMarque

( @MRQ_ID INT )

 AS
 
 BEGIN TRAN
 

 ALTER TABLE ARTICLE
 NOCHECK CONSTRAINT FK_ARTICLE_CONTENIR_MARQUE

 DELETE FROM ARTICLE WHERE ARTICLE.MRQ_ID=@MRQ_ID
 
 DELETE FROM MARQUE WHERE MARQUE.MRQ_ID=@MRQ_ID

 ALTER TABLE ARTICLE
 CHECK CONSTRAINT FK_ARTICLE_CONTENIR_MARQUE

COMMIT TRAN
