USE [IN5_CAISSE]
GO

/****** Object:  StoredProcedure [dbo].[SP_SuppRayonSeul]    Script Date: 04/25/2012 12:03:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SuppRayonSeul]
( @RAY_ID INT )

AS 

BEGIN TRANSACTION
  
  ALTER TABLE FAMILLE
  NOCHECK CONSTRAINT FK_FAMILLE_ASSOCIATI_RAYON

  DELETE FROM RAYON WHERE RAYON.RAY_ID=@RAY_ID

  ALTER TABLE FAMILLE
  CHECK CONSTRAINT FK_FAMILLE_ASSOCIATI_RAYON

COMMIT TRANSACTION
GO


