CREATE PROCEDURE SP_SuppMarqueSeul

( @MRQ_ID INT )

 AS
 
 BEGIN TRAN
 

 ALTER TABLE ARTICLE
 NOCHECK CONSTRAINT FK_ARTICLE_CONTENIR_MARQUE
 
 DELETE FROM MARQUE WHERE MARQUE.MRQ_ID=@MRQ_ID

 ALTER TABLE ARTICLE
 CHECK CONSTRAINT FK_ARTICLE_CONTENIR_MARQUE

COMMIT TRAN
