USE [IN5_CAISSE]
GO

/****** Object:  StoredProcedure [dbo].[SP_SuppCaisseSeul]    Script Date: 04/25/2012 11:52:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[SP_SuppCaisseSeul]
( @CAISSE_ID int )

AS 

BEGIN TRANSACTION

ALTER TABLE OCCUPATION 
NOCHECK CONSTRAINT FK_OCCUPATI_ASSOCIATI_CAISSE

ALTER TABLE CLOTURE 
NOCHECK CONSTRAINT FK_CLOTURE_ASSOCIATI_CAISSE

delete from CAISSE where CAISSE.CAISSE_ID=@CAISSE_ID

ALTER TABLE OCCUPATION 
CHECK CONSTRAINT FK_OCCUPATI_ASSOCIATI_CAISSE

ALTER TABLE CLOTURE 
CHECK CONSTRAINT FK_CLOTURE_ASSOCIATI_CAISSE

COMMIT TRANSACTION
GO


