CREATE PROCEDURE SP_SuppTarifSeul

( @TRF_ID INT )

AS 

BEGIN TRANSACTION 

 ALTER TABLE TARIF_OF_ARTICLE
 NOCHECK CONSTRAINT FK_TARIF_OF_TARIF_OF__TARIF

 DELETE FROM TARIF WHERE TARIF.TRF_ID=@TRF_ID

 ALTER TABLE TARIF_OF_ARTICLE
 CHECK CONSTRAINT FK_TARIF_OF_TARIF_OF__TARIF
 
COMMIT TRANSACTION