CREATE PROCEDURE SP_SuppFacturesSeul

( @FACT_ID INT )

AS 

BEGIN TRANSACTION 

 ALTER TABLE PAYEMENT_OF_FACTURE
 NOCHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__FACTURE

  DELETE FROM FACTURE WHERE FACTURE.FACT_ID=@FACT_ID


 ALTER TABLE PAYEMENT_OF_FACTURE
 CHECK CONSTRAINT FK_PAYEMENT_PAYEMENT__FACTURE
 
COMMIT TRANSACTION