CREATE PROCEDURE SP_SuppSousFamillesSeul

( @SF_ID INT )

AS 

 BEGIN TRAN

 ALTER TABLE MARQUE
 NOCHECK CONSTRAINT FK_MARQUE_ASSOCIATI_SOUS_FAM
 
 DELETE FROM SOUS_FAMILLE WHERE SOUS_FAMILLE.SF_ID=@SF_ID

 ALTER TABLE MARQUE
 CHECK CONSTRAINT FK_MARQUE_ASSOCIATI_SOUS_FAM

 COMMIT TRAN